### ISSUE TITLE
[1.19.2] Advancements-related Fatal Crash 

### ISSUE THREAD

**Issue by HalcyonSeas73** [MC-U-Team/U-Team-Core#216]
### Bug description and reproduction steps

1. Load Supplementaries (+Moonlight Lib), Useful Backpacks(UTeamCore), JEI, Farmers Delight, and CB Compressed Blocks.
2. Using JEI, give the player some Compressed Feathers (of a variety of sizes) from CB Compressed Blocks.
3. Game Crashes

Perhaps related to conflicting advancements? Error log mentions UTeamCore, so I thought I'd post here.

### Log files and Screenshots

Log is from "production" single-player world, so has many mods. 

https://paste.ee/p/cL4zR

### Used minecraft version

1.19.x

### Used forge version

43.1.43

### Used mod version

4.3.1.231

**Comment by HyCraftHD** [comment]
Hello, the only mention of uteamcore is in the "ServerPlayer" classloading list. UTeamCore only screws with the Method "initMenu" in the "ServerPlayer" class and does not do anything related to advancements. 
I think the error happens when a other mod modifies some collection in the advancement handler while it is iterated. The cause of this and the mod is unfortunatly not that easy to find...
Probably binary search for mods will help.
