### ISSUE TITLE
(1.13.2) MusicPlayer Not Opening In Forge

### ISSUE THREAD

**Issue by Jonoz1** [MC-U-Team/U-Team-Core#24]
yeh, so I downloaded it now (plus the u_team_core) and did everything like other mods,im opening mc now, and it says that the mods didn't load

**Comment by HyCraftHD** [comment]
Hello,
What mod did you download? This is the issue tracker for uteamcore so I'm a bit confused.
Please specify the versions used and paste the log.

**Comment by Jonoz1** [comment]
oh oof
i downloaded musicplayer

**Comment by HyCraftHD** [comment]
I still need the exact versions and the log to help you.

**Comment by Jonoz1** [comment]
Music-Player-1.13.2-2.0.3.32 And 
U-Team-Core-1.13.2-2.4.0.110

**Comment by HyCraftHD** [comment]
I'm sorry when I'm getting a bit upset, but I need the log also.

**Comment by Jonoz1** [comment]
its fine,how do i get the log, cause im an oldschool guy

**Comment by HyCraftHD** [comment]
in your .minecraft folder or cursefolder under logs/debug.log or logs/latest.log

**Comment by Jonoz1** [comment]
[debug.log](https://github.com/MC-U-Team/U-Team-Core/files/3586498/debug.log)

**Comment by HyCraftHD** [comment]
Thanks!
Seems like no mod is loaded. Are they in the .minecraft/mods directory?
Also your world seems outdated and may cause issues because the format is very old.

**Comment by Jonoz1** [comment]
''Seems like no mod is loaded'' Exactly, when I'm opening the game, supposed to be written how many mods there are.
''Are they in the .minecraft/mods directory?'' yes they are.
''Also your world seems outdated and may cause issues because the format is very old.'' what do you mean? I didn't open a world.

**Comment by HyCraftHD** [comment]
> ''Seems like no mod is loaded'' Exactly, when I'm opening the game, supposed to be written how many mods there are.

So forge could not find any mod. Either the mod folder is in the wrong place or forge is broken, because 1.13.2 is not a stable version. You should definitely switch to 1.14.4.

> ''Are they in the .minecraft/mods directory?'' yes they are.

That is very weird then, because as the log tells: Forge is the only mod found.

> ''Also your world seems outdated and may cause issues because the format is very old.'' what do you mean? I didn't open a world.

In the log there are two exceptions when you open the world selection list (click play singleplayer)

```java
[06ספט2019 18:09:49.985] [Client thread/ERROR] [net.minecraft.world.storage.SaveFormatOld/]: Exception reading C:\Users\Lior\AppData\Roaming\.minecraft\saves\blueboy\level.dat_old
java.util.zip.ZipException: Not in GZIP format
```
and
```java
[06ספט2019 18:09:50.197] [Client thread/ERROR] [net.minecraft.client.gui.GuiListWorldSelectionEntry/]: Invalid icon for world Time Loop - Adventure Map
java.lang.IllegalStateException: Must be 64 pixels wide
```

Theese errors are still unrelated to the mod loading problem.

Maybe try this:

1. Please backup your worlds and other important data from minecraft
2. Move or delete your .minecraft folder
3. Relaunch the minecraft launcher
4. Relaunch the forge installer
5. Drop mods in the mods folder
6. Run and see if it works then
7. Copy your worlds and other stuff in the .minecraft folder again.

If this still don't work I'd recommend using the curseforge / twitch launcher which will handle the installation of forge and the mods for you. I have tested it right now and everything worked for me.
Hopefully one of the method will work 👍 

~Johannes

**Comment by Jonoz1** [comment]
k ill try it, be back soon

**Comment by Jonoz1** [comment]
yeh not working, guss ill try the curseforge/twitch launcher

**Comment by Jonoz1** [comment]
ok, so i mean i had the twitch desktop, but now I couldn't download it, but i fixed that, now look at this, what am i supposed to do? its modpackes, not mods. btw i checked musicplayer, nothing 
![modpack](https://user-images.githubusercontent.com/54620172/64490715-abaa3080-d268-11e9-8bd1-8eb4ae913ca4.png)

**Comment by HyCraftHD** [comment]
Create a custom modpack here: 
![grafik](https://user-images.githubusercontent.com/7681220/64490742-7e598480-d260-11e9-8b39-c2e4979568ca.png)

Select the right forge version and then go here:
![grafik](https://user-images.githubusercontent.com/7681220/64490748-903b2780-d260-11e9-8491-9d44a75323e9.png)

And search for musicplayer and install it

**Comment by NotDudidude** [comment]
i dont get it, when i opened a new profile and then what?

**Comment by Jonoz1** [comment]
damn it actually works.
thanks :)
