### ISSUE TITLE
[1.14.4] Channels [uteamcore:network] rejected their server side version number during listping

### ISSUE THREAD

**Issue by fuzzyweapon** [MC-U-Team/U-Team-Core#26]
**Describe the bug**
When disconnecting from a multiplayer forge server with u team core and useful backpacks, client gets the following error in `latest.log`:

```
[Netty Client IO #6/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channels [uteamcore:network] rejected their server side version number during listping
```

_Note that this doesn't seem to cause the player any negative impact that I can see._

**To Reproduce**
1.  Install 28.1.26 Forge client to vanilla launcher 1.14.4 instance.
2.  Install 28.1.26 Forge server to vanilla MP 1.14.4 server instance.
3.  Install u_team_core-1.14.4-2.7.4.134.jar to both client and server instances.
4.  Install useful_backpacks-1.14.4-1.7.1.41.jar to both client and server instances.
5.  Launch server (not LAN, but is hosted on _localhost_ for this test).
6.  Launch client.
7.  Connect to server with client.
8.  Disconnect from server on client via `esc` menu.
9.  Observe client's `logs/latest.log`

**Expected behavior**
No errors.

**Versions**
- Minecraft version: 1.14.4
- Forge version: 28.1.26
- UTeamCore version: 2.7.4.134

**Comment by fuzzyweapon** [comment]
Found out this was because I had an entry in my multiplayer menu for the live server (which had a previous u-team-core loaded).  I think this invalidates the bug and is by design, but I'll leave this up for you guys to judge.

As a side note, it seems a little weird to have a client reporting that they reject a server (vs a server rejecting a client, since typically, server should be authority).

**Comment by HyCraftHD** [comment]
Hello,
This issue was kind of my fault as I have forgotten to update the network version number.
This was introduced in this commit https://github.com/MC-U-Team/U-Team-Core/commit/57975fef25b4fd52b871abad01308099050db165 which changed the value.
Nevertheless the client version and the server version should always match. Else there might be weird issues.

> As a side note, it seems a little weird to have a client reporting that they reject a server (vs a server rejecting a client, since typically, server should be authority).

Definitely agree that this system is kind of weird. Currently we use the SimpleChannel of Minecraft Forge for our networking so we cannot change the behaviour there.

As this is working intended, I'll close for now.
Please reopen if any other issues occur.
~Johannes

**Comment by SDUBZ** [comment]
having same issue with u_team_core-1.14.4-2.8.0.140 and forge build 107

**Comment by HyCraftHD** [comment]
The server and client versions must match!
