### ISSUE TITLE
[1.15.2] Curseforge tag ambiguity.

### ISSUE THREAD

**Issue by plaguewolf** [MC-U-Team/U-Team-Core#31]
**Describe the bug**
Doesnt work on fabric.

**To Reproduce**
1. Install on fabric instead of forge.
2. Load minecraft
3. ???
4. Profit

**Expected behavior**
On the curseforge page, there are options available to tag wether a mod is Forge or Fabric. Please use them. otherwise its just chaos and confusion.

**Screenshots**

**Versions**
- Minecraft version: 1.15.2 [Applicable to whatever version
- Forge version: Latest as of report
- UTeamCore version: Latest as of report

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
This won't happen because curseforges versioning system is the problem. When the version is tagged as forge the minecraft version won't show up anymore. I have tried it on an other project and it lead to more confusion and many more wrong version reports.

As many other mod developers for forge don't do this aswell I won't change that.
