### ISSUE TITLE
[1.16.3] Crash on startup

### ISSUE THREAD

**Issue by QTPieMuffet** [MC-U-Team/U-Team-Core#52]
**Describe the bug**
Crashes on startup with useful backpacks

**To Reproduce**
1. Start Launcher
2. Start Game
**Expected behavior**
Run with useful backpacks

**Screenshots**

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.41
- UTeamCore version: 3.1.12.185

**Log (if crash occures)**
[debug.log](https://github.com/MC-U-Team/U-Team-Core/files/5685856/debug.log)
[latest.log](https://github.com/MC-U-Team/U-Team-Core/files/5685857/latest.log)

**Comment by HyCraftHD** [comment]
Nothing in these logs indicate a crash.
Furthermore uteamcore and usefulbackpacks seem to startup without any issues (as of the logs you provided)
I'll close as the issue seems to be not related to any of uteams mods.
If the issue still persists and you are sure the issue is with uteamcore then please repoen the issue.
