### ISSUE TITLE
Please indicate your mod actually has features. Or better, remove them.

### ISSUE THREAD

**Issue by Moleculor** [MC-U-Team/U-Team-Core#57]
Nothing in the description of this mod indicates that the mod directly performs a feature. 

The mod includes a Discord RPC whatever thing, that screams out to the world that I'm playing Minecraft on Discord.

I have 115+ mods, and tracking down which mod was doing this was rather difficult (when trying to diagnose a related issue), and I wasn't aware that I was installing a "Hey everyone! He's actually playing Minecraft!" announcer when I installed a *backpack* mod (that requires this mod as a dependency). 

Please disable the Discord feature by default and/or remove it entirely in to its own separate mod.

**Comment by BluSunrize** [comment]
Yeah, kinda worrying, if not predatory, to have that mentioned nowhere on your CurseForge page, and then also make it *enabled by default* in your config. Feels rather shady.

**Comment by HyCraftHD** [comment]
Thanks for the report.

First of all I want to emphasize that there is **no** bad / malicious intent behind this.

I want to clarify why this mod has the discord rpc feature. It was first introduced in early [2018](https://github.com/MC-U-Team/U-Team-Core/commit/6131e7bd598f649ad5db59131b0a304e62f7631e) as a request from some users. At the time there were almost no discord rich presence mods so it was kind of a unique feature. Back then it was listed on the curseforge page as a feature of uteamcore. A year later many other way better discord rpc mods gained popularity and made uteamcore's kinda obsolete. As a consequence the feature entry on curseforge was removed. However, the feature was not removed because many players liked it and it remained to this day like that.

I must admit I have never thought that this feature might be undesirable. But I'm stupid. Based on your report, I can understand that this behavior looks shady.

Right now I'm not sure what is the best solution. Removing the feature completely / Extract it to an addon mod? / Set it default to disabled?
I will keep you updated what I plan to do.

Furthermore I'll immediately add a notice on curseforge about this feature again.

~Johannes

**Comment by starmun-0010** [comment]
Please disable the feature by default at least. Just spent most of the productive hours of my day tracking down what was causing my custom DRP to not show up.

**Comment by HyCraftHD** [comment]
1.16.5+ will not have this feature anymore as it's now an extra mod.
For older versions I publish some new versions soon to disable it by default.
